apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo
  template:
    metadata:
      labels:
        app: argo
    spec:
      containers:
      - name: flask-app
        image: andriibesaha.azurecr.io/argo:v1
        ports:
        - containerPort: 5000